apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pod.yaml
- service.yaml
- pvc.yaml
- config.yaml
namespace: app
images:
- name: app-postgres
  newName: registry.digitalocean.com/jwtracy-personal/app-postgres
  newTag: 20200820-2108
