apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: app-apiserver
  newName: registry.digitalocean.com/jwtracy-personal/app-apiserver
  newTag: 20200815-2246
