apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  ports:
  - name: app
    port: 8080
    protocol: TCP
  selector:
    app: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - args:
        - -v=10
        - -alsologtostderr=true
        image: registry.digitalocean.com/jwtracy-personal/app-apiserver:20200816-2157
        imagePullPolicy: IfNotPresent
        name: app-apiserver
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
