apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
spec:
  ports:
  - name: apiserver
    port: 8080
    protocol: TCP
  selector:
    app: apiserver
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - args:
        - -v=10
        - -alsologtostderr=true
        image: registry.digitalocean.com/jwtracy-personal/app-apiserver:20200820-2108
        imagePullPolicy: IfNotPresent
        name: app-apiserver
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
