apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  externalIPs:
  - 68.183.249.43
  ports:
  - name: app
    port: 8080
    protocol: TCP
  selector:
    app: app
  type: NodePort
