apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
spec:
  # externalIPs:
  # - 68.183.249.43
  ports:
  - name: apiserver
    port: 8080
    protocol: TCP
  selector:
    app: apiserver
  type: NodePort
