apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: app-webapp
  newName: registry.digitalocean.com/jwtracy-personal/app-webapp
  newTag: 20200816-2320
