apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: app
spec:
  externalIPs:
  - 68.183.249.43
  ports:
  - name: webapp
    port: 4500
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: registry.digitalocean.com/jwtracy-personal/app-webapp:20200818-2238
        imagePullPolicy: IfNotPresent
        name: app-webapp
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi
