apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: app
spec:
  externalIPs:
  - 68.183.249.43
  ports:
  - name: webapp
    port: 4500
    targetPort: 80
    protocol: TCP
  selector:
    app: webapp
  type: NodePort
