apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          serviceName: webapp
          servicePort: 4500
      - path: /api(/)(.*)
        pathType: Prefix
        backend:
          serviceName: app
          servicePort: 8080

