apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml
- apiserver/manifest.yaml
- webapp/manifest.yaml
- postgres/manifest.yaml
namespace: app
images:
- name: app-apiserver
  newName: registry.digitalocean.com/jwtracy-personal/app-apiserver
images:
- name: app-webapp
  newName: registry.digitalocean.com/jwtracy-personal/app-webapp
