apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  externalIPs:
  - 68.183.249.43
  ports:
  - name: app
    port: 8080
    protocol: TCP
  selector:
    app: app
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: app
spec:
  externalIPs:
  - 68.183.249.43
  ports:
  - name: webapp
    port: 4500
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - args:
        - -v=10
        - -alsologtostderr=true
        image: registry.digitalocean.com/jwtracy-personal/app-apiserver:20200817-2022
        imagePullPolicy: IfNotPresent
        name: app-apiserver
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: registry.digitalocean.com/jwtracy-personal/app-webapp:20200817-2022
        imagePullPolicy: IfNotPresent
        name: app-webapp
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: app
  namespace: app
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 4500
        path: /()(.*)
        pathType: Prefix
      - backend:
          serviceName: app
          servicePort: 8080
        path: /api(/)(.*)
        pathType: Prefix
